name: Update profile readme
on:
  schedule:
    - cron: '0 6 * * *'   # every day at 06:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Generate README content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.repository_owner }}
        run: python scripts/generate_readme.py > README.md
      - name: Commit changes
        run: |
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update profile readme" || echo "No changes"
          git push
